name: Create Issue in Main Repo
on:
  issues:
    types: [opened]

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Issue in Main Repo
        env:
          INPUT_TITLE: ${{ github.event.issue.title }}
          INPUT_BODY: ${{ github.event.issue.body }}
          INPUT_MAIN_REPO_TOKEN: ${{ secrets.ISSUES_BB }}
          INPUT_MAIN_REPO: TestingStz/Bug_Bounty_v1
        run: |
          python create_issue.py
