name: Copy Issue Title to Bug_Bounty_v1
on:
  issues:
    types: [opened]

jobs:
  copy_title:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Issue Title to Bug_Bounty_v1 Repo
        env:
          MAIN_REPO_TOKEN: ${{ secrets.ISSUES_BB }}
          MAIN_REPO: TestingStz/Bug_Bounty_v1
        run: |
          TITLE="${{ github.event.issue.title }}"
          
          # Create the new issue in the "bug_bounty_v1" repository with only the title
          curl -X POST -H "Authorization: token $MAIN_REPO_TOKEN" \
          -d "{\"title\":\"[External Issue] $TITLE\"}" \
          "https://api.github.com/repos/$MAIN_REPO/issues"
